spring.application.name=intern-assign3
spring.mongodb.uri=mongodb://localhost:27017/EmployeeClaimDB
spring.mongodb.database=EmployeeClaimDB

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# Logging
logging.level.com.assignment.claims=DEBUG
logging.level.org.springframework.data.mongodb=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

